version: '3.8'
services:
  mysql-server:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db.cnf:/etc/mysql/conf.db.cnf
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    restart: always
    tty: true